const common_API_URL = 'https://localhost:44376/api/';

export const API_ENDPOINTS = {
    BaseUrl: common_API_URL,
    User: `${common_API_URL}User`,
    Login: `${common_API_URL}User/login`,
     GoogleLogin: `${common_API_URL}User/google`,
    Register: `${common_API_URL}User`,
    GetAllUsers: `${common_API_URL}User`,
    GetUserById:  `${common_API_URL}User`,
    AddUser: `${common_API_URL}User/register`,
     ChangePassword: `${common_API_URL}User/ChangePassword`,
       UpdateUser:  `${common_API_URL}User`,
       RequestPasswordReset: `${common_API_URL}User/request-password-reset`,
       ResetPassword: `${common_API_URL}User/reset-password`,
       GetAllSchools: `${common_API_URL}School`,
       GetAllCountries: `${common_API_URL}Country`,
    // GetCountryById: `${common_API_URL}Country`,
    GetStatesByCountry: `${common_API_URL}State/bycountry`,
    GetCitiesByState: `${common_API_URL}City/bystate`,
    AddSchool: `${common_API_URL}School`,
    School:`${common_API_URL}School`,
    GetAllGrades: `${common_API_URL}Grade`,
    AddGrade: `${common_API_URL}Grade`,
    UpdateGrade: `${common_API_URL}Grade`,
    DeleteGrade:  `${common_API_URL}Grade`,
    AddReview: `${common_API_URL}Review/submit`,
    SearchReviews: `${common_API_URL}Review/search`,
    GetSchoolDetails: `${common_API_URL}School`,
    GetAllReviews: `${common_API_URL}Review`,
    GetReviewsBySchool: `${common_API_URL}Review/school`,
    GetReviewsById: `${common_API_URL}Review`,
}
